etcd:
  userName:
  password:
  secret: im2023mi # etcd 配置密钥

mysql:
  dbMysqlUserName: root #mysql用户名
  dbMysqlPassword: im2023mi # mysql密码

mongo:
  dbUserName: root #mongo用户名
  dbPassword: im2023mi  #mongo密码

redis:
  dbUserName:
  dbPassWord: im2023mi #redis密码

kafka:
  SASLUserName:
  SASLPassword:

credential:
  minio:
    endpoint: http://127.0.0.1:10005 #发图片视频文件需要填写
    accessKeyID: root
    secretAccessKey: im2023mi

secret: tuoyun #建议修改

tokenpolicy:
  accessSecret: "open_im_server" #token生成相关 建议修改
  accessExpire: 90 #token过期时间（天） 默认即可

messageverify:
  friendVerify: false #发送消息是否验证好友关系 false表示不验证好友关系

push:
  getui:
    pushUrl: "https://restapi.getui.com/v2/$appId"
    masterSecret: ""  #需添加
    appKey: ""  #需添加
    enable: false  #true启动个推推送

